# Generated by Django 4.1.3 on 2022-12-07 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingdetails',
            old_name='content',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='bookingdetails',
            name='date',
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
